while(1)do
if(Stylus.NewPress())then
print("NewPress")
end
if(Stylus.Down())then
print("Down")
print(Stylus.X())
print(Stylus.Y())
end
if(Stylus.Released())then
print("Released")
end
if(Pads.A())then
print("A")
end
if(Pads.B())then
print("B")
end
if(Pads.X())then
print("X")
end
if(Pads.Y())then
print("Y")
end
if(Pads.L())then
print("L")
end
if(Pads.R())then
print("R")
end
if(Pads.Up())then
print("Up")
end
if(Pads.Down())then
print("Down")
end
if(Pads.Left())then
print("Left")
end
if(Pads.Right())then
print("Right")
end
if(Pads.Start())then
print("Start")
end
if(Pads.Select())then
print("Select")
print(DSLua.BirthMonth() .. "/" .. DSLua.BirthDay())
print(DSLua.Color())
print(DSLua.UserName())
print(DSLua.AlarmHour() .. "/" .. DSLua.AlarmMin())
print(DSLua.UserMessage())
print(DSLua.Language())
print(DSLua.Hour() .. ":" .. DSLua.Min() .. ":" .. DSLua.Sec())
end
if(Pads.AnyKey())then
print("Any Key")
end
end